### ISSUE TITLE
Еще одна ссылка для работы скрипта

### ISSUE THREAD

**Issue by L3n1n** [Kasp42/Steam-Fast-Farm-Card#2]
Привет.

Добавь еще одну ссылку для работы скрипта:

`// @match http://store.steampowered.com//explore*`

Может это конечно и опечатка в Steam, но в нынешней летней распродаже на странице стикеров указана ссылка именно с двойным слешем. 

PS: Спасибо за отличный скрипт.

**Comment by Kasp42** [comment]
Сделал
